# Generated by Django 3.0.5 on 2020-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('duration', models.CharField(max_length=5)),
            ],
        ),
    ]
